# This is a basic workflow that is manually triggered

name: Deployment

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      environment:
        description: 'Select the target environment to deploy'
        default: 'development'
        type: choice
        options:
          - development
          - testing
          - production
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  deployMaximBio:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Checkout selected Branch
      uses: actions/checkout@v3
      with:
          fetch-depth: 0
          token: ${{ secrets.PAT }}
    - name: Display selected tag
      run: echo '${{github.ref_name}}'
    - name: fetch assets
      uses: dsaltares/fetch-gh-release-asset@master
      with:
        repo: 'dsaltares/godot-wild-jam-18'
        version: 'tags/${{github.ref_name}}'
        file: 'maximbio_build.tar.gz'
        target: 'subdir/maximbio_build.tar.gz'
        token: ${{ secrets.GITHUB_TOKEN }}
